swagger: '2.0'
basePath: '/v0'
info:
  title: HCA Matrix Service
  version: 0.0.0-dummy
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
definitions:
  MatrixRequest:
    type: object
    properties:
      bundle_fqids:
        type: array
        items:
          type: string
          format: dcp-fqid
      bundle_fqids_url:
        type: string
        format: url
      format:
        $ref: '#/definitions/MatrixFormat'
  MatrixFormat:
    type: string
    enum:
      - zarr
      - loom
      - csv
  MatrixResponse:
    type: object
    properties:
      request_id:
        type: string
        format: uuid
      status:
        $ref: '#/definitions/MatrixRequestStatus'
      key:
        type: string
      eta:
        type: string
      message:
        type: string
      links:
        type: array
        items:
          type: object
  MatrixRequestStatus:
    type: string
    enum:
      - In Progress
      - Complete
      - Failed
paths:
  /matrix:
    post:
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Join:
            - ""
            - - "arn:aws:apigateway:"
              - Ref: "AWS::Region"
              - ":lambda:path/2015-03-31/functions/"
              - Fn::GetAtt: [MatrixPostFunction, Arn]
              - "/invocations"
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/MatrixRequest'
      responses:
        "202":
          description: "matrix request accepted"
          schema:
            $ref: '#/definitions/MatrixResponse'
        "400":
          description: "bad request"
  /matrix/{request_id}:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Join:
            - ""
            - - "arn:aws:apigateway:"
              - Ref: "AWS::Region"
              - ":lambda:path/2015-03-31/functions/"
              - Fn::GetAtt: [MatrixGetFunction, Arn]
              - "/invocations"
      parameters:
        - in: path
          name: request_id
          type: string
          required: true
      responses:
        "200":
          description: "request found"
          schema:
            $ref: '#/definitions/MatrixResponse'
        "404":
          description: "request not found"
