language: python
python:
- 3.6
before_install:
- export BOTO_CONFIG=/dev/null
install:
- pip install -U setuptools
- pip install -r requirements-dev.txt
script:
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
