language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
  - secure: fPA66ekcq4KknHYfMtUXJwCOSsaZO3NZ8vgUwrIATC0IA6EsTOHqOMDwKwcoaSaqLVyIsZB8LHb2RSbAbnSz6G9JDcnKAhx4c1hps3Pnl+NYkNRTOaGRAHOt2unfSOsJGpQiXtyLUbMGv/Y2ZntpImLdoA5chsTB5aul6pdfszQLKwrdlOWv2nmajcW+qtQTvW+bnEjLQ33MGyaCyuKEvdTcuhD2N4xZdgcE0eB++jVdXHr83RSdjFtPlUMYRcRA4l8gyZVZReLOJfXIKMKW7luG9hesOAU0E33bh/0ThU76+QPVjeDvn2uBtYD5ir1Ek8qrwpYI1rXhNA5EUMPAZjAKHaY8UOuAsqkHlzZ4osh+sxshqyNyyf1bjCEECX+zUQBu6abSeIFjNdS77J4QD8IGjFOcGh8PvkpUvcjDGEEqIhoMsQPRI1Lg/DuYoU7LvlFrJOV1LI7YEGfd1qmf3V5qFRKnICd+64nHqUE7NAUQiF0wC/K/2avvx/YrN11d2JxJaFSVcbDGm5qq0v8ro7k+PcAZuMp4oTGukTzS6RVlLnkFSn/sFgNAziYKL9g/hXmkAFQY51W3PY2+qC8opy5Lw4fMPP+HtlecK9CJNacW9HLOsDRqsfpLrC3uzPp0OKM35S+mxkWZBdssPd6XsXSooNGN6LPMP+LNX2r1YoM=
  - secure: ebg6GuRV9ijHsBmRbzpLKf6+KEmopIAU61qtvsMtxp4xKX/4OhG4YEFlbKWXj4KFAuJr6ZRbVWjxqdHnqkpcDk0H9HXhuSZEzYGqXB4CPSysXTVsplFp/ANDt9xJia/SM1YFHmT2mcT/7FLASaxWfx3LC1jDCdtTMZIOJWfeCYddWCpPdlCwbnCgycSNSiQTgpBj63y43EW2eNmuK5hxItAmURJWLsRvLGZGbMZKosB6ZzU9y35bkzXZNk4EaNv1vZZthd+MvGml6ZKF84HoLUxGuxwgcyD+WGtLoYyrLemz0wPCTz9ky0222SKJceCiNRSbU3a8xYuC58GbFvdbaoUSvEMle8OEewh+xtr2Qx0QfxgkjEuCivE1sJofujVgOPwXWHg5u8+cia1qzZshBakjYA5dTFfvRlTocUGMZwqaRcyntybHaFVBabRoT7YvNqHphlSzMsWpKyLj8GFsGs8aByMvwXlZ1bBjWuVSMybRqummDbkTt3y29tRGyYW3JQ1OcLwk77di6SM58/1q735bc6O+w1MxZL5Ac8hHzcOOLM90jsnQzph06ns9GtPawK5wWjXv7CfFlM2umaEnUXnH6pHDO6JN3CuQinJfMYlrGEWjje9B2NNXw9gcrbiZ8d4DsZuHxCjRyHO3cxJuCaqeu/rU+RW5GBzU+/qHN0Q=
  - secure: qbMNMGvnSvtvlxBkifRxUz4zC1xwu3N/ErtMDugmTZgD9izcBhvCijZ+jhvPbjJpfFZ0nJR7cvWF17b+jjRlaPNSaxKV49McwdN7DsQ5ysf+VC9j4idrSi+sLdWSemm78gUYUa4oXvQBDdfl61wr77gUeuIxngU0TCz/bMu1b/dC6WzsHnTf96dpO9ik8ouTCorUI/4SfqZ9CoQxM/lQ9LfF0CRiU6w0TE6Yket8tUrKmRSDshPvEtsWUCShA4lHyCADkeEpZCDGS5srHNqda+nDZM2ZaabiCt3iLbCMJHpj06jOcf6o4rsKpKZ4vDtrLGZDrFwclBCJHyC+R1ga4HZo6WO/Sm2D2rIvgyS6XU3os30J7fGVbB0VWKwmV8VT32WFKt6b1LdYTYEXtRIA3w5VfN0xU2Mm6H/Q/Y+1kL/9924+LS0GcBC1thiuBDzmHwqKFv89JGUOCAfEwv28oETX7qnyE7Dl7kpzBsjWZMBLxGYKwF8eH4sOQDKpSToplyvXcvGRGYWkJeVUghXVf84vNkCsyRO5MU3Vnc98LbBhH5NQMSx2G3jUAn1htspCZUdxnuHztuuGDueF4Hx05+xmtc13kkuOQ5j+k7LZatA5hT8RsoQl4KQFRWHqwXhJ3JEsv+3B6rHX2JsyTZXn3IiM4XbDLZ5NZFnN8Ota2tc=
