language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
  - secure: Z0qRFqmm7S1AynKOIq3YWGckB/LwLSlCEO+LlMVtcUmn+5Bg5dS0qA4rJSzkZaQgYxYc5rdJ0KRQbzYGAx/ejY3HYo9KqeWGm52AubnwSpF8ldsMkbK0Y+chAb7rBC6RXdJV/dsLL6CR/zustbhtT1kXutF1iAvs5SYb7DQFHg5OpwRz4Hz+W4YMpwQ1P9WWSF2ixTWJxJoCsRrpD4RWP4uwgx5mHfSvZiOoy9ntSKOXzW1G1sdxk6d46Uk/TAGeDxWboTjbbg1P2tYms6qUrnHFTscc6uXpYfBMqNenWJtmgTZv3vkZbF8tfcsAzxZ9TZt4nmzUoQZ7zHnY367QTynJeb6xVR142obLdvMFLK2PkHpo4h4KW0HPPU6N7OtBKpeKqX9+awopEzcdtcwIzMm10amLt6aTX0DSaC4YxqvKiCSAjmAKWaN/hs2Hfg/3THtJxGjz9udljUn4+tgYhsdKkZa3nIqnkmak3n138Wt0TA6ZxeAB2wgQqUX4ZB6iMiwLk2vpGbOv9N970o9m+VZAt4oAXsHgpY/xwbO4MS7idd9jdpOTvN1z8QPaGf7r6hTpDXY0+DER8I78Dyqw/HBuk9sEydM0OR+GlGofXRUYYeymmZnqFeUZbZhAJ8uj0EVDugeT6SR+i7TbDdO2h5XlecbYNHQNcgz5h459wsg=
  - secure: lDS6xJtT1FtbUmkbtiD8qvvP9PQQQ6i1q1ar0zdQ1xMfzTpAq0br4vygrxQoIpIk5ywKcI+ED/o7xetYgQg2hYvnnLsMIUwPtAGUjIWjN/s0vCCwRb5dQH1tksBDq4LANQmyYp+j7k8b+3pyUH7C6TTD+KjfhQUkanJnMejAnseSBqWEsV2GwpulSn9nt0YTtbNyzq4eo6m9OrBaAGjcn7VU2CSRoUGP+Mwxr4wT7WtRbDyXVqjmvTRKwSef3QMLUY5xMOWINWSpDHDOyi/bK6TWotliDZS+WniprN0ya4+ZQdRfdamD2SYOf0AlUUZYDUFsU/7LEwqvbetPN4HQGgJCvhsri5KYVzbgKbYlY9ybpYGUhp6Bp+i6vr74MbYY+heiBd8bKDOgO7kBQV6xCxPrhW9W8ny1BVTu0yJZ0ELcPBSs5zQBhhLvYPnlmVymK/r9XWLNQfhD0OLgZ9vPzt5SJYusEdBHvUB5thZAfd2yEiSAdCQa2ydLKIxX5fJ2Whf3n+rx4Xor6IvO8v5W/gPI04QB3EcliYbmcMshDOAQ7RspyRZrfy0OkMs6a4IzdSw0JbaUnUSlscdBW8n6HotL21dQdxx38kUITKfBfgbIUa3wlU5SVhO8tBIEk/FP0SOMFOwtzO4FJD8z9Ab+ILCxeHRV1vN1NgJPErvNXFM=
  - secure: ktmFyi7fRPIV5Ywhbaz4Bb15HCmZ7U//SKux5G/Rc6GOEQzSs1uLSyC+NnlGaeNUZ4RSALLoKznTYbMUROix2nkqgWHF8YYKgEcE52NBLc8/n0DAYmAMheeKJqDcuygBNlU+rLQS+LUOiHESY2y7ksNMTE28ZxvRHxYsEljFzZwsseRi+pGNIJ1tAEWocrjRhnYyOL4LV1jb7hG4PTvz4ys75BS0t0QSfjxCDXWlsiQH7fjyi5MbvaBY/f/zUpYJRn7fRECOfO5IHCCn6bMlVYte7plfydGzA0bfB4Uvf2ls0egyIc7+8ZOye480p45/E5gk09u8iBuCG1FVjQWzNCMoCTCz2Oo0AubeHnm8N0DjLmm1XyHb6F2+M5//kMkKWLUi5fQNaKqpRQ+F/lpqgeYmrXgcRVXq8ODi94EqoJB/8CGXJJ9ThOS/bR4Cllff4CbegwxRbz+Vh4NfXuJUySlv2dWN1rf9B1o8UwZJjTdMCfJjEBy8wxHGyunE/yM2KiUza2HrAYwDJGJ0HWct+Hw9d5Jed+Ad3hSJ3tMubFki/+udLucqo85uGmJ+Xs6qRhd8Ik/6Ld7uAm2L2XeiIlA9Qptb4PLAgegZxmHLUWXDh8sLdCYXocImFb/BhsH/HEjBoWzc2e6VyOSPlx/gnYHV/1ZMMa/ANFvCiuxcIy0=
