language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
  - secure: ZwE+8wvTbK/QJIJ7WmMBl+BiBw/BcmC7JPJniNMjOk08Vc8fOccJzPMGpuQuDk1iODnPGc0HAljxdfMcceMBPpfLf5fg9WODr0qDo+puniifKKeR/ZVr5cp88JZsM73mXpjUAP03yhq+rhE/G09nmJ/yyVZR226DxYkuXer5N4Q5hdmWASJW2EVNACE4/+lR7e98MlDwKebhtPbjo55Ad9UsZwS6WeXRL6hO9WXA2/bWU5VsQinpX0zrBRrPaEHc5ffJ++eeHwmkq/Ex+8ywfEeCairamzKrb1gg61w/9felM4mVURvQ3l/2Xx/oyz5OnuV8ETQDaqkskiAw4onwv0N+cFRHdi5oc8KwPYFzDRvr0oYlukftY2Pq9MhE9q2MNTdoeCVeedTdQq/88fT+myzlR7rJ7mBO/AZr140UyB6WEiMmO/5yzRIFEun7dCIOd0RAhQlYzgAJpgbJCOdPXTRuVdBem15loz1UQfW+GoXHVDyVqNQtpmyllYX299doAtsvhC1B1TOnT5mF0RwnWMiDb6mIDHmWrqnRlvcRU+yVqm0NOFdV5elpLasdL50U+EHuDufbKoev4VEr0A7eF1B1NYXQGMpAmsc7YihJxdQK6xK/0Z/1v6CwKlHKH1f1v8RR6yXQevTbTHwLo41N1SuVA4cpQfmW3o2jR2M+k4Y=
  - secure: SsSTho3gxYLHiGUbEB9SGFDLywmbOZ7U2oX6Fh3Ta9evM22FNSJtKtaasGfEpx3/DU7jg+c3KddPBCDMv5k2e4XKCcTGTxkPacEbLnQNlQQ/DNgVIsgNuAk8FmqoLlujgdFsXtYQat71tPGEy8ymilrGW1VoFPUMVl7/sz1dIVntWPC3Q7fexbyb6cbhkUu5kuLtJGjQRaNhzyTOCDkV3lTgjTcMrKX9ewhJi3VOxRWrdIluxHNZfxIMCvxiEkwxySKcutCqJ7D/MLD+eV2nLQjE8RuHjlQv+sp1D1ud/wq8/+kYSlQrxqqCe/HjOeo9V84CGw3f5zSnyWRqeHKL0XDHBIdVrTVMSD7TRWdJiehrgqIYUthLdWp4cX+M+pwnQunnO6da6BoVYgO6dhgIDw6IcOr30Pns+FBuW/gn79z8iHfWMXtj1sdBU+YMiK8ApP48osSuG7rucW/OKQcB8y80cCtnIpW3BPa00XsMssKIANfGLzLbn3PYj0Ad4EExEpupgW60n1/p059W60U71rewJjdaz9N/BNX+f8tymPKwQ3L1vXmsVYHUr04ZEnglU/P7z83X5raT5Tpx6+VOvydhyyXuahRLGWFchJ8mF6xS6M0M2LYjYE2uQMEIu+aGGSKhtROnH+lZwvHDffYD1iZHDbw2mzDHdOJp4lh2qv8=
  - secure: XDmiJlflvi2m7svhRJRkl+h7jf4wjKu3cWOpPHrUpppmzs9N+gBjHi0jO0DqJ24Wms15/wcYRJ3V4nHnMFwVRIlRC8Jo2SG4BLpEp1wXKpKIWQUJuV2O/nKy69tZToVdFNTLy4R4zbO4bybDy/3WssosljpP/lipqBnQuzdOqZ7rs7HP3YZE10HN8tM4lMOGj/OoWRe06c9EsJFv1pkCN2N4Aukb2/v47YD32KawWbOO7DW1mDiqSFJgXH/h5T8ZCrMpxJIBPtkdzab/TbisCYlTNQLOvYZTeeIS51pwoHIgxPTYt1W9eCHb3sp+Mmn8O9NW48mBkW6qO7juqNnCmFPf7oNuHsGL9W9oXPKZfmXOHQNFCHeuxjZzibVX861ibjZChvQLJ7btyimj0XhvwaaKkR/4AG/rlGfFgC760QwhhnINxY+r1FiBaQ1DWGQB7Y0+63d6TRRebrnAMGqLy38ZXOg06gOeF3HWI+hGfBWWD6mLLvtgvetA1RnVQ5iLfdGzqojv22aCkiu7VQ6OB54f4wMPlyG85GFcevgS7c4lDygEpFtmQCoz+fDx1rbr7zS2hrHateY6Z5oCdYn8rkmTssLoLrucbtUEZafBN091iEbjd4FZ7e3e+vpx/zniL7N+4RRjCTn/NjjYbxHLTbdYIzHODqcozVRoBBsNmJU=
