language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
  - secure: f0sn6Ct/uv6g+pE/zUb2t2vw4wBdUQtNVMr7Y8T2uyA530sR4+4d5o6XRReOqcSZ2ga0gaTd3H7XIhOiduCv+YpvRDMUu5U+Qr2vOGocVAH5E/ISwN3ERqi7t9gsgniK14IhRaANBmUx7I+FTC9R27LoVe+mwcCBZwNIp2Y8NA3CnxSWChcu9UC72esG0Cd/qmbWcCj6L0ALeIkiZrW9rymUGYaR82Ze1TFNoKnrk/iXos5aIFR21HtaN7G8rrDOCImreuHC33loYkyitzTmXZgvN8GuaIoYI/rrHjp74h+Qq2U4Pu1SkbQD1Pah3iTrn2jWZkcvJZzvxxL0ApiA/+Njnrv6xO7NvRtxEhensDZPdIlQ876gBt0SCh8nYbHdtRffxq97gr0dyAL5O75Iw9ekYmOclSgbru8U81lerM762rLPfWmSbnqF2C9gRRwf3ZqGfKFDlhfznTYIBY6PvOPErCAlfshXTAizZvoWRbVwPxfGnY9j+OR9L9MJC4epxi/cZByZ0JzRITcRy2I3R9hyPWsgK8UoTRuiAL0dBaEruJQ+8BlMs18h6rX9/kF5ot3uyVqfj3UkC3/mpLTSxjMQPa/iO3lH8zQ4ZFca44W95q0OdPJlbaHfu23lUQLmgZkHO2zR1nD/pS98DaRYyMhbDxqVi4zwi2CHkDBquno=
  - secure: O0mTsLG7h1sbIpc7+jTmgXMFc+jVEj7RS3sIxgzog3XfHe+cJfsZfe6MhmcI8iBsWnG6gESygau3aaf4Y923Jxo/2fpr2Rrbimzya+JLLaouXmk57PO36NP9T4LxWBp9IvI4akmZrHj+ccWECOdKry9k8j6yhuzxXZbxJOAd3AphIch6WSGWNjJPfmfsLe8TFArMsuPdvNwv6sFtJphbWwK2ZXHBXoW1ZUqj1MKeOwBhxdWE8mLfsc2hcCY/QhatclHB1UUM4EthsFTKz1oXr80r6NSfIFV6H8IZLQWRTt/ht2ZRz57/1ojjIozrZu19uWjHGZ8KBf2PMfSR0F5MJzlplceBTJFCBiiJo+57t2lgA74+rRRNBnAnCwqMTBx9KaORgmsiVs0jlwrRLiYHW32FO2TLDpzaCgU5zxjoAz1a6v6xY4q8zz+ZWRNC9QaAu9EC5IV4P8ICUvx5vs6jvtoqTNqGwRu41EYi6crgtzw92Nlu6rNkzUMuwDNwpfoMu1MIPrdiJ2pr/Yu1f2NoZkKdX7S0CZnYl1bKSWMnVy+S+gXYlO4IqH0/2qbPuo+kc6PuDcBmg7Aml7GwN99PPeivb+ISmrZtlZwWMjy2XsOB1o6cGsxb/Eaboa3VMhCQ3bCEdhgaVs2hJITyHs81y8Vx+95dvm9kCT4GUz9W47g=
  - secure: eGXrFRSp5Si6tuRtXpc6M+Sd55itZo9N1F40x5DzFptfp6C7yR/7W21GSzmv6DlRc0mIWH+/zfQW0w9BpRJFc/EMzjq8nDSfguL1xm7pth7XjN2cpNYRBleUPjNrHBmRDmfy9ApSvKK3r4imKZXL99HI15Fo2ChQ/8jRhkCm6qYXnVxViSWuPiNmEnmlKpFeI3o6vRoLrEZD8Au5ThN8dolRBcVn3HzbPUJAaxKhArqKoA9gH8AIxRig7rFvLaL1mcPhgwiZgn+OXicjL97Hf699YUIXrXoc0suN8F+TwRsDRTA9npGwiPBS8Iu1IBo8+z6TGNzU7MLep3wzCMIyxjSs+AQkJtzgLdsCGXpnWT4PvzJIu91cvkgy3YRpajEwNejr/mIOrRO0ZkluS2gEv7hqTIrfht9XKdr4txD/eXxMlF26IcgxEeLWuqGqzWNkq1d033lDsIWvVvM+HVKTFG02qbbYyebE3rHuf3XB0g+nDnaRERNa5TDg8UeaRV/NEAAb3/3u1tOnClqGa03pIT6XmgLo4Pl7kSUzlSQMn2bKOLX2CP9j4xolo5gpvIkBA9l/3b1rZXbZT63Od41hIa9htCLNLtE/InDik4oiFySPFOkJbBoloQQsko9CxXbwIYA7XXNzrrM4JSZNh6di0XyMuSu+kx8oSVwUagIoGSo=
