language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
  - secure: RO8qLrpdBHu1dB/DebkNJL3O62Oqq8V4XMFjItY4Lj8aEJux2lTo49q9wYOGtcav0oHG975VJyq29IMVOx86id3aHGWh6Q6/yCpAbL5QY3KVrSMhE6k/Bn387jJHDNWN7ZRVmMNdwPu86szRkxtO74fo9ztNo5Akk94JGTZ0idi4yOw8bqL22iLnOFRtHse1HII2ltHB4OJTIhXGQe6jWgzepTDNW6h8foAPm7vpcc0NJjDeZpxLQ8TJoR5orWWhJW4B6R6jsCLCqLZF7GxAaXNaj+IWMXUO+ZeMiRZyLcSb2xWpGI5g2sBLnjZKLsJJjGzO+i9jjzuLp95qB9H/aJYtifRjVTEC+4CMZhqfyYC1t49Z4qBo8T7580OgD3PIyovf7qkQcb2nZ7MdHs+YlPoNE2/m9GShsitfqFxeOfue5L0W4fZbkNwKSbp0JOf4NuYkJgC6nfce1rPf6+l45ixJgdV/E4lo4cCV26ucoq0zg+PLPw5VNwnygFgyhxM64X+CLPDrVEAHbANjTNDLyIpVl/1r9ejgUlgMm7Hr3evTKUPuqDXz66wd/NLcaQWfpd9WOVTsyS4Owo27l73xqXHfbvcIAC1j6SsIWXkc27HuspGSCVQBSPRuhC/ezrA1Wmzof+3Jg/75BF2qYJAOdFCkpgsy1ijJH+SlypY+9DU=
  - secure: sHDYZlmDIBL7JaQLGApqSQy3blAW63lX3NKF4ONQukoVA1NgIyYRhWqmfJqW0TbxKtIRfZTbFI9ExZGzV1LKdkyztCqGDgVDWS4e8YHP5aDGcyTEd54SI0wbf3DW/d0QeJGxEfxoL+3rqL0T/cJhMaXwrXl+dxhcwmVCo6kLHDAu0cmBvlQ+HGsKnGq4hHnBYo4O3aqQnbaar6NLNI+35t0ZtCOE/04Vv8EDGkBxhoge1lD7HGdMx6oyPmVyAlwOcgPKPxK0l/xtbzsFB9igGwgUaG7+XaT08l+eRk5I19JMgZHXiulsrS9Uv2fqZshpLnnzzrV8sK+OoL8yF6t8DhKMQI2/i6YGbcpkE9f8FhT7K/RPJ/V0Sg2bGdzgXtgPMHwDbtEmHID1nXxtCVaySJBdUNDcF+jwlgNtKVv7NFoy+XufQXwvPxI66lDQ6FIByIqnJODu5XyZ4URVP4i7I8OgZxi1AwDvI38gRzYIHbTEXj5GCguHUmuWZGmsZW6j7AjGme0rC1wAHhJXO6FX/tQOk8Xjs1KJGuuqVfNaxKMs8Sof6BR4+7uWeB+Mw8DasIWX/ZewDzsQporxOLCTZUzXk6Lsnm3DNqNrNpUqZJduWgA21UfmS6086R0R8x3qbsaNvIMHQKYf65LyVYx8GLDuFxTALAmeWxQYKez7ANk=
  - secure: MhhQ9CT8hoCFY5mkFUFuroGlSTrakDnG/0CyGaFRSbevS3AswOmFBReNRpGq6hTEHxsEkN8u/PkTP7GIqatQUzklPPIaQCM2WUzQJJ7GddEpGTmW04FW5cOPViIufwHuMqbQD5i75Ijwikg+oaGi81RgAEn6TRRppYDFnW6rCqc293BEYpAozG9S7iP1VjG27Y92eaQrOwRohmfmSwqKEYt2zKJ16BF3ujcCBfUaknpWsA8//yMJw15u2Rr+BD9F2DesWGMj5KP040/sgR/f37mPcSgaFj0F36eqZMWNrRjV6QS2qLFiGPpm8Wcw9lAZxgK+G3gY9/sqStGOC7zJ9s5SFF7sywAMtGUGT2+PtzwSs5fQDKVTnz+QsYT+ZIyObdG5VIwU74R6vXeAYvyf7kD7hWCxBsFNHJWhqzoNK8X80L3MLW4BSEjXKBrgKBe9dK4I7vs26VN3QexC+Ot6Xq95FcMvveZghiQHYy5f2JHjX7x+k9eH3BeSYZcJk4HNXGsb7w+g1i74w5jVynnx0Ata1Cdj95/cKemdzBXe139kdDI1aP0aQvDnwUkXhmfY0QA3M8DCTvxFd+u+Gm9Gc21c3P3ya33tFJphCsENvDRAN1UWqYGaZI4GoXkllYsfKY75GDMd5J1v/EFKX9OJJzbEqdRzdSdm+/SbeMHjjzQ=
