language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
  - secure: FfcpN9TV3oKwMkpEYCenNO/JJjAENk8f2h5P/89GptOhxPQuv8vj8mjLmWn33Gp85BX+qdyqWQpis5/1yxSxiwm4vOnxiljz1gcFSd++yUMYQWHk8XaBv7xCWaqfZea1a9NiNCF32e/CJLFXJaF/7xFVuZkPMFnWuayRmxqBYyETiahRYi33BULhI8eCaO3cLNu6Rb8LO71jrHuhAXiXdmI/4uLzKD6SGnug3SElgGqhKFR/zmu5UKKMN4zN1Te/tV1oAms4VI7+/IEQKv2EZDpU8ICdcTrY6xQRAEsYbEPFq+vP984AVYKR+9u0cyz3qYw+q7P/G/ANAhn/CFswT5/amwBApAIaw9ZYLVzAsBEf2ZpcUU4fNcgwbZHIHOeGZkdHCkJasXQgfFLqFc8daCJkoF8Ld2ji9AjxThaTug2mCxjFdt5mesdkOZidVcXlTkCHHLZILFDBFUBGmVgAFdn63DyYG8fs8bTTRBY/Wa8fBV33WBZT69EFABrW7tiyc0Fn4NuBROD9QkL3NVo2445hSiQUtcSmDeq8k5zjRJRWiQsOs2hob+OScI3JHEc0xbKN8V5+90VIx/SXK7oPuBlGjcAV5r6OY0F6sxRICuYSPP1PcZNGWL71MffQDcM27HsBt4UkT5aP4jc1NggRW0HmZnPXo7fDEUXiqwYtmR8=
  - secure: KVBPG03K0n/ejObXlLKSpo2td0ciesd+4lN7GkJxRZ51R/2mXb3G/p0wRQqFruGfoP984M+hWtQIQqWpWaOuddqdREzoYDHsLE8ZH6omjZJwG2TtcSEfk65avxQpD0vDXVYmlkJ9DB4EBZHkav3IE9nI8BBEdslV7d8DXTI31dKggKrVYnZD3A31svZ5IQ90pna68wAt6di3I8y8QooIfnglChtUrZCVFJgkHz2xm0hr+xW+zIqDnSMrthS46VoN7F2BdLqTJcvJL31aq6MeKxjRfFXfI6zqt0tsThz1N3qKaEP7VIZTw0nLhq0nbJt8mHYLVbE/cpXdT0NLp12WzQDaQ+DeKS8S6lY+5jjyweRx26NqVZIlUr2E4zgcjTFqUAFwWVqDIfZJPTCdAFhv9/fBp3kGrPxde563bFp3VU1x8nWHmy4oCzrYM7zrSEO2F3Gd2YGT80Gnz3dMop+9NxZLHlCmbJteu8dR8ZhKuIF9+jA4MCk+PqDQcFtS4XmAYFcpdmyRU0YA1RiflRuJw2SWOV1PZ2qyNwA8fN/tUenRQgfQSmnvL1g+gjI4ulb2kkclk/MipiAg/V50DBy2TP0REWsozaLxBItWilHyAR+7NMjZ2IGXuKSvwtVQ1gpAcBVkIZmpgNt1dDZPODp8cdoVbIkxfmley+vvG7zKdgk=
  - secure: rx0KsjGaBFqyLDlLrtC9zkAipe4/ReE6c5zlenGH+JzFzQ3aLWoow14CQ7djleVXZLN2H4zFAgMnVeJYgmBQWLRhtX5kiU3frHJjg9BU7jCqVfetSAK731iMlpBtS1ek3yIMRIGa9nq6YB9Fcy/h9hmZQC8riYRrRPva8n+gxIJ4dPNmj96i+4CRfmjLT6oOvQHbW4pHb8gwrrDVOZNVcn0hLBZeaQhiHurIuPK2PNe15p09Pc5SLZc6+JGvcFyFK1NUTvCYzy6KIP+b5Ch1z8wGA/gYMiMTOfIuGhKgAuKsF7Ts18qToNXJ+b4Ww+6Ns45eSJxGoRzZkmTWs+4kd0f6SLC9nDCqupzb76V5lFBjmh5Mqc1HitL5wi/1pufL9sWdVxmDI8uJderbu7u3gl+4FvwcGVXEjmJq93Zr+L2ZijFJ4qZBKKg0AUkmHbQKn++mXXr5lx40vQ8NWx8h45b2zor1RfuZDHbJ/9MbawwaDjdxGF2U8WJ1BjorgJ7FDvK0+SOQRnBqhPqIH1ms38nKPUm4iwPGoDWhC4T6lD6gblTdeneRNhhURcOkpyKC22VNBDnBXW+Cqk9H3qne1Q25EGGyFgPePtzU2QPgKekwY2r/811dvp9roew7dUt56gkHTNvS+3jwqPdzWZiY+dMghRfzySHvn7Dbe964NNs=
