language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
  - secure: PUF5CEjhfPhUt4StRAyKJczwy/q9zFJ7mmzlhXELs3n8mAWnoGoyI84DU8z4Xu9xn1l4o3HiCxzJUP1urhvazw0NHNW5FyFhGaWxRFCsmDkVSeGso7dwLi9A6QWgR4qUmEeaXX7tKB4tNFjtNB8qpkpzugTOg89H8wvWjwOtk1KUmO1ywWx+rLOOJFLCHD/pwMqJFjdQ03uA7EB382g92HwfDd/Yr4aIDgb4y+sv4v8fVGsW5rXONmMhYeCGdg45QoX5EUVYteELAGE7MbzYBYfPmV1BFeBheQD3UV0EIhbmllZz2mrmf4zym6+N6Rvsnb5fn5OkKJRlF7994dBokmhDw3dbS0cSXwFYvM8kUf+/ejzfA+UTxZWWQ5ridMGGx8ie0hTIwuMoY4GBWXzuz6ePjFfYMNDADwi6MkCHZhtqcN4huZJ5i7vAVVnWKFvlX9B9NYEoTAew50L/qi7qu6y/IkRliZLlMVYV+r7bCUptJD57r57Jgk4n6qUxC1Ufc2gxoC+a11fDY4QbU0xJM/T3UZpahKl5YOxBjNTVMvaDna9rumRfHU1nYvE/mGMNmeb43IuBuzgrwhk69n+hN8o/1Dv+zaDCJRw6xOiVzb325AnZY4MMeAG6rmjNtorwrWlex6tPg2CeqkW01PTLwdOZ659BEvw4NUvI6UOmH/o=
  - secure: a5z1d3ttW8zF3Lwo4YI3zCn66BcAG2dnQy2O3vA18WEoP2qjoFhhm+E4B0ucOFVxPXqfSRPBUST/91NssL9Ibnua/BRxKV7HXO9GVfUjHHpBX1Mu/vVwdAljqVYw6Ca3NfstfjcS2W3jwboKjbeIaRFGyCmIArr29PwxKPJeEtGKBxp0H+9EfZvcMcCpCtweGE3xs7SEZlFRqzkmRbsFljQmrGPCHNoTb4xMC/bDEwzmAo1BmcQCdH5bfbO8r2sWmHP9E2FTrmkN6ClGElGA7JPHbbQkzvkHzBwiDBkdW6JkxNzB/CYYZu1q5PCS+3VqikaN4CaFGtFvcoihRXzGbb9Qal6LolwKN/27iDN0tfhXJNxk9pizzIcUjOKO+SLETpou3zbgU+R87YGNHSHyeNdfNxhJz+P2DMVITf4E3S5QPnCIvNrBZaArcKhcvZDGxW3Ql26wuH3xXtClAJWa4GyckuDzeCvsmlrx90wGW7OjQ+RY4Z5qXwKtrB5xiHt3WWe8RV4fFs+ra/rD7cyRQhogQ8YVcwUhL53ZrOxU9l1TTkOz68oT0eKOEcx9V/p6U7MsBwxUh+46xjyIObUzG2K55HQ4K5F32iAlicaMx2taEwo3wxERxxm2hXH7DhpOQ4SpE+2XP43np2FkiuN3apdww4LEq1NfxNdXroI2oaI=
  - secure: X3S1ZS5tBXCsJpPxelXknQ4xkN9f4RdqWnOEV+g145UAZX5e+OISvIIk7eh/sgRaoKYIeWF4buYvm8h2T62hrpusoY/C2Rj062e3RQ+jyniIu1uTlomElUUNfo9kTVzv29mmOxC8jPU7cJgBHGmXmMbWG4Q/BhUaEAW7bxs7YuXhI/EiegzMJF8MnXD0CJ2d3Md1kqDFOttKxuSbScjCwQTOA+5nf3fEv4Am4cnPGk0DoCEoUdI/WU9YAWoOnbY74ZxopQPS4wR+qteQU6q7dgWH/UUk8E7zsc8wvhj8iHsJaM36jIgZ9Ldmp6AFO8NTBXkxQKskDbzOECAowaLceVSs1eBIsNpcIEZun3VhZ2wwETmvYeRy+n19ekuT9Cmwg2HRPGGc4YJ+5n+4vwzXiEzM5PllTScx9COQAzzhTieYS1NumpO/zZsgP+xPZDAEIUmDRLTelzuqWz88o5FjSarK2CARvK4v9oh8u7ctYcMX2/TaNtRfNRsyxBgoHb+pjQM8jUAdiO2xLRuae4LcRoci4RYfT0HdLHW7Oh/FzVoGRyAgtSYppLCGf8W21tEWzvY9Wc/x2zgfcTrhLapa+G5EVveWXKrr0LLhuOVD5bxIwUdE1S9IOR6cGsTKuKKRfBdyjoh/CKyGPHbn4z1SfQahoENpSKIWm3Kg3798QQ0=
