language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
  - secure: zy7ZG1FBO8FkuZc4KXoNLqXfOku8pBZRBqng02M7yuIdlbZCvi+dVQTGQAuYg4ZCCqA+6eXDMSalkzEPmQmZMUvgQMDwpcg+t5iNGbn9q3QUsauRsWK5idQbn4FncErzrUnQEK1nuQ0ggbNfTFN4AupJNaRazZzbDi3GvTMjHa6czH3g8f4vZKs/jjwub9Jkt9doriEgdRLW81z8YxdLAN1gpkt1p28Dcbtj0Igh9rI3Bc1E6fjYMm3AZHeemSJgeY4yAdSx6XFJwaSPZX//jJV2fHKS4RRNv/xNdgmkWmTJNmi2qiUeYiOLx1BxuYY+2VmahfDPu4wnoVecbGfDyTMGitELCO6MfDiND7soCeshHRKq/VP69s+vZVtPlgJ7xG8/28fAyVorIHkmFlXnuMkb3ZoGN9sOtxqUUSSzrUFXH/r0hfG6pAFGlfYgTAabb19JGDSojjqhO3aAULIdfyoqRacsx4M8XBprqQ6QeI15y9F8anIDebPVdWXhImio9EVVuqonflgF0kbDKjycq4jZRWAGqSk0A415/+utcggAdiBDFwCLOeaCOfqchMeEKdrba3p+o+iZ6XXbkd11XoVJNJ7BPq4jEMybhPW5KrYJhoobcUjIEk2RUo2iGkvX1W9qIGBemkyEXo4oqvTC8NaGOxRNA7e47D92Y6ipLp4=
  - secure: GzLzPU6buaRcdeRlJs6Nd4ddWlmXS4+Zpck/v4/vHGJJMyGu2UWAkhCCTLMrsz4aHZXJcAC4Ipq8pMVgLrJ/HEH8DpkUP8wfN6loarvwRUgjeNAuzRWPq+yerio4pOFHCww0vPDIZ5PdL4pKHo2WUBE64MamWsc0wi9eIUVETv6BUoIUyWa7ayntQKBjV0wd/prwlXBQmBYXdw+E7qXa/tvotGzDqnHDHIitNhOymfHEI3ZOvwoGL7sRZSD1mtz057Hw8+E/0fFmas5QJDnORbGq9KuD2Y9ERD2Ie3pEtgskrf53SnnTzWIoCA5W4+Nl6vOOSpcUt+yCRDM2VDmidUCNfmfhdICob3M/MYXQca8LsnAP8C0bwdh2Q8OzSYqtgkpVvFpxb1XJb4HOMAjN/mEKeolRw9wazVvlyO9KlwsoshYxGZIsIJP3avdZu0U3tAQIxmru3s9J/mLsC8hPN65zdyB1tJUW35XENlMKAnY62v//m4ew9r0HXjldBcwX/pl7+OUlk2P8BpevyD1ghXV8aBRtf1Ul9Gmve4r9sD4V8x/1EjmHgIkOmDnqeJE2S40bbUzSEOF6bOyb1GsCKlBssk+hMN0FKI5PScyC0U1szS2B6vRB4Ad2EIz13rr55D/pFJSfdYyM5ekRnW/Npbi9azCR2xTt7mG/5ZLJtk8=
  - secure: E+lqy+XnFyGYIYHJ9tXgT35Iqj16mIsLVf6WSrxzqViIJq5KOgsWBAskQAuphrJXvdQWPGqrdyc0anBtx+PZUH3t23wGjpb8UtMHRA1SeGpkvcG+096Js4b620qFrCsAfI9t4/mfAGshsDqsdIlZd7X3IxyBSZ6ILBxxQQyH/pnnOL9oCuCqcB7VfoDVI1Zh4JyqtCa3Aj/nndy5p77sRcT1NOf9b8d6EpRYzwGCITJn8pxJ1TD/gpqP8S5F/OVrBaxW1WfQzoITDitpPs8Jk7ZpiV5p6AWiRa2bZ7BgCI1VAWTtmjjMLo2WSQDFyb3O+sxcuNYTyfeOGGOB2ysyciEuyuyjv4WaKIQGwQjxCwsjwhDPEtsRu8Qgi5AT527puOc7OA5i8gSUtirdYypqabh3vKv1iJIHqocnv4YUpq3G0KDCQpGtIC5I0mPxpPFMOEO7pNBtNnGKRZ3u4M7CioIELCxngV0GWfUlPIIBj9HhxPCcA4tz9UwgFEPYmCdomw7THC+QHxfSLwUQqMw/S2OlTPQG1Nipx3sCcM9dgR9BNNbkvOgh8FO093ysgANs+Ei1UmJPpXFxEI8Mo7jvELC9wSTroRNQtM6TSBpDmKwCfeyIhs/aPSFMfQlsc1HIo255zzWn8gzdJ9qDU5j65eSOtpq34a3n/6vazJPpk9w=
