language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
    secure: Kiqi2uYT7XFG65nvft3ZnO29jyiiVEYMQKqiR0HGJD/yfm6pZUf1Nt4YEqbaBeQueVgzK2OUuoCeO6u3NremupktqgJljbZybVrvXtkpVwNmqMWE9zcXYY9EOVKvx6aY38z2lEcUSwu6gy4FdPe5z7CsEt0W215Lf2zrX425MYeF/CoZBBabnMBGUVCi/BLyTHglg0tSWD7SCs3AUIm/nM344gomfW3dEz8DWOUpcLLHiAK1Lc8elBJwdZCWgGF5e2AY0qxwpzCMBcNeAzkbnK8LgQMpReTl9ACB2H5K7Dsv5Cx7Z7NSDPwyCm6ZfAj8/unNHXvNw1TM8Xb7hcosT35zkKLJv+mFXUWy8XIBpcC3ZawG4zPDFMttEzkiBqP6kXdTEub/NzAebCyQQ0Ujzsht1QFm823huebXJPNLvnb6Yzo/1cbOUo8I/e39aZzAFUH1Lqs6yWcZFzFslvXFStwkPHRz4jyx9AiSSRN6j/LXqSNbXwmTCmHKYdrlzCgrjSqhtH52Bto+41PoNNc8TzL6/h28P8Nej5FCUsAQd5o7HzhKzcfZ2Aht52qgdd8jQ8wpubKIJSmdrA4ep25TGkEweAEgLKRFdjG3qBUV9lN0OaeOtce/ppz26mUyCiGBL365QiLDHeE5ZyLrMNo32DuZZrIoYVN5fgq9U9DTiZk=
