language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
  - secure: P0ml1Ga6JNDQKwTvvdIMeW8IQr+H5d3Y+4pSmcNpRApyV1Vw1KMdEUIJYnI/DT+iNlLPMMmFTiPvZDulKtrULiMRx2TugA8gciGZZrFiPOhHi28/XKSIqA/J75igr4pA+9yYSbu6YPzPA8Ge0NOIHA977G5+h7El+tMG4cE4HKsx0DcdavKfnVCfBK8V6SdQkxvpPGacR7V6LQ+qw86zR8Rxz92v7AvOVX9AhZLUWgax64A7BX7pEEiIu7fISYz9cPTqh3aKgmLH4pTH4s7IRsAJk+LEE8iys/KOSROXsT5QNrN9ekw5EWQeZfIG30hq2y5lQjQmgikixEBwzB003RBu5BOrXtm6E5i/utQaGRqLEHNZh65OjskPr49RA2YPsYVjAArjk/VeWoiinelw5QIZvgNxqzuCNBdXrvsxT0gkefOH3oroLz43TIJik/v7F0Rg4iaT3XuCu+wpU4sSVWCFs+OmF35Z0eY4KZ2c7Hu8Vp8Zu4yghYZZCI1rX5Izp35z/Fgmix4frGnBSdoPEabAGiLHxwzGPsFGzxsmk2INFmxZT8CYGjEtFBh6D/+o5LZ5NMUam9ei9BMXlNKR3+Ry1YVxAD+dAyvDyU+gscf9UrSu2C5NLoKMOrPNSUD6Efa6BEJ8eGTpzWk8hcMCeOaSuqTsuF0JA4BqC/dBrsk=
  - secure: Wt5YPO7qjnvbZBToje/lEB4ZUW9OPB3sp20G/UEiO+NpYOxHGqQiR2BVzd4Z1X/hiiyD8Z0sl4GgNgU+45hRxS1qTxE0605y8ETeJc4LA4Ch+iMqPwpkS7i2+5R2/Lte3QUucqdiVjWiNEQkT+LWIS1GN9zaesfx6r0L5itxzqfycmxmBQuns3j7gpcfB7PsNFe72ZArpehBEW/gAzdIbc0Qq14TcjaI3OnViNdIEqZGu0b4+wyGyrGLBo76KKJdfEN3g65BHHlKmEwMldR0PNcHVE5ZOQoDwbTdEF4gr5wFb69mvJWDeaxjJYQhrb3GCArx6ZF2mJQ51P4QJIV1cSKoiF1KHhTTOBajU5zmdS1Xae6Kai0f1WfJSSEqB9DCe3N9bdf9Gq147hVPNkytOK31luq1MlYs5w657EoRzpgoZjbnOQzLsQd1tDoVXM3P/uCIV+B04Va8Z/pr2ehhPWKIzKRcmYC7U7MrOGjjoXYIyfeEk0DgIq0QZEtIijV3BxcoNGbMVmdwoQGPr+7VJ9h0NfO7BVGN+acBt4k5GMgPzI+EytKQfqGp1S6eMxHwb9zNhlMqC+mwwj0+R3Or+JxONBde68hANS6eiFLR6jm3vWdqNxm/LnbXtjVjWihbI5LxojN8CNqAlbMVyHTzGjTBw7CofeQPnkjqRNv+zaA=
  - secure: JuM7+caUzF0zJcLzf3hdDns+8+pBtlAN3BE5niAJ4mPUPDhSA5M8raqNBdwjEvZOffklT7Y04CYMTeJJsf3/uZvFpm4nRB9Qurt2jhhgJqgkCa4RK/iv5pqWgNUJPkYCHYOukyDNC2pHMcVMQaYnEWapljCk0eDck5Ioi7LNpxmCOmmOkxjAzcQNJ2y+M4xPlbKgk8p3czMxBgQ1JMi3TotOjSEWrBjuvkS4X/AFhbdkRE0VR8ltDsOu2G6zdwMs4fI6HDJR7rv2tTOKCYoJWUnlT2HL0bWdkFLnlPHizCweli1+NiXT4pGTkTHUOqxA/YBMpWegsYL23o7LuYRtttWSL0/ugnYQhuFGyOWyGgCWFtCfTlIgaa5On/TZpSyzFRrkZFGLosr1jP5BipDSpxw/OF16axpnfcsRXnrjh+iKt35lDDpgO0YzKfJh78J35Xe9PNA4njGRL/ZlUavCk3evSHxLVUtu624Xy7m52laplHJCIeGOZvnkpXunmVTiPegwFPd82pfUmJrjEeLWG09KAOHHj4590feQV5OChBX/Z1TrwfY681vLEYq4yOt0AYbB5YYcEXkjNnT6Ak5ag8B3npZ4pbsKmVfNh5K7YStBSkixEdRp0B65BAOw3rY761UsRWgqzbEQIIXDkUg6qzEySH2ImX33QhjDQp0dlEo=
