language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
    secure: PUF5CEjhfPhUt4StRAyKJczwy/q9zFJ7mmzlhXELs3n8mAWnoGoyI84DU8z4Xu9xn1l4o3HiCxzJUP1urhvazw0NHNW5FyFhGaWxRFCsmDkVSeGso7dwLi9A6QWgR4qUmEeaXX7tKB4tNFjtNB8qpkpzugTOg89H8wvWjwOtk1KUmO1ywWx+rLOOJFLCHD/pwMqJFjdQ03uA7EB382g92HwfDd/Yr4aIDgb4y+sv4v8fVGsW5rXONmMhYeCGdg45QoX5EUVYteELAGE7MbzYBYfPmV1BFeBheQD3UV0EIhbmllZz2mrmf4zym6+N6Rvsnb5fn5OkKJRlF7994dBokmhDw3dbS0cSXwFYvM8kUf+/ejzfA+UTxZWWQ5ridMGGx8ie0hTIwuMoY4GBWXzuz6ePjFfYMNDADwi6MkCHZhtqcN4huZJ5i7vAVVnWKFvlX9B9NYEoTAew50L/qi7qu6y/IkRliZLlMVYV+r7bCUptJD57r57Jgk4n6qUxC1Ufc2gxoC+a11fDY4QbU0xJM/T3UZpahKl5YOxBjNTVMvaDna9rumRfHU1nYvE/mGMNmeb43IuBuzgrwhk69n+hN8o/1Dv+zaDCJRw6xOiVzb325AnZY4MMeAG6rmjNtorwrWlex6tPg2CeqkW01PTLwdOZ659BEvw4NUvI6UOmH/o=
