language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
  - secure: dYISB/kky5qHMQdX63E0wvVfIEXX81+p8H/yF9La8zjHFR1xkIaZkG0vhSBUppzX7/66+FK5y7PRdIOgI3eQtQK48DXnp0YGsPd8hv44N4Kk4z+DPPYoTcuVGcdktePVhzvuYEyRt6FUOlBHKjt3A/wVc0l3K4eAA/HRoGGNoSNdsPn00NTGbjsJ3/W+mwDnbR4J2rDsbb3mSnUZJYz/dLr4irnjrltNusRq5/0A3JWaJfEAiETAKfd3f6eW/ObEBLehQd4Kyd96mQpk48e9dm9qMOt196hJ5PAeADBQHUZqleZTgh9mzkfnbL7C0BKSy3dXcv0vpoBjUpMsK6BW4OcEjAOeqk4NMUW+fXoH+MpRs30WBjfq6iXkoyndcXyKizf2ymizOzv63c+jH606LLZFJtRbXB4PMExL3NBfn80Aoa3QD21YYA5Tb/7ygXUwyLVhhcme7k2Q0RLl8N1lpTcjRc87b7VGpLMb37PfC+IkUpPaGxgdWezLRtj5TuTmOWDfsJI1QrTwYKlg5eGI8Iw4AGBRQVkX2uzFjdEZ1C50vH0EMqErPckDYYFj/ysbvadhtVDG5kyf9P/SKO0Y12RE4sSK8w+j84A3cujmS5TCik3EcrRI/AgpJItCFpxI5pw6ShtOoIkRusd942riFifOsc6V31sBJtvqPzqb2Fo=
  - secure: MqontuYkSmJht2okk/NlF8y6yHRHI+dZHvJi6HhGDXSNkoDKpXEX0movZ+CwFUdZZAB58OKdwwrflI2C0pn5OWx9+PtU3ZvJrFk9LtK6JgRxIhik3C25P/Z7mOY7SR1nKQQJLp9DK4Cwyx7KXT4BoFrjNwK9gxkBP/YNX3wW5qkGTQZfDIXdN2x+hMdapJ97N5jW8tanVkVPOZnEieQjhoCJIHynPU//V5mNtVuddOnzm+JI4I33L7kQJeubuGZGVhzhysZZN+OKj4zbpUJGajLI3vzkWWSTh26WwYB29pie5nh3leToJet5pK3WSCaAT3xnzisBkm3WlAioKJQRKDn3WzN6W+2njoPGj6WDyiHL/YN9czDTYH01D6n0T7NNJllfzfM6F2TUkbQe3Jjt4GSdkbR2h65p5O14jCtQg1suu5oi8oXQtbGnUhf0UcyS9MqbFHcGP0xoLomrAOGVQvc2IJmSFLNxmmpr2/sH9g720/sBjlEURuDVbPvRNm3flv7L/Av3n5nsnoAW7DiFQ8k9nHJ6BG2LYiE1PEnUFBkOJO/B85/akXkKXEW//V5LE0vF7u+ta7F2tYffuw5HaxgX1BaNcTTkAUeVMZK8wwisrH0KXJe3PRT3cqI58Q/5ePALepVzJLaAwy0ImLT1kP7vJv8RGzBt3jhdj8tUcFw=
  - secure: APVeBuD2+cD/sc0LRXFaX1+ADRmPbG6tllS40vBrKR89bfmbvux+u4eo/DT9OWV+E9eSEbDKzn+uAHKIGgFwhQx6Y+NTX6GtKxK7VxldWFJTDcnm7r/HY5FlZHGZf+z0RAB63vRQ9vqwJCVUzi+F5gpjyi1R+xZWUVocaUmSSt+sAdfP/+u2+0c2tMxlOTdUgAPdJENtSSmEebhbVGIhorBxuNFVVtE/nYvIsSsNwpRU5NPZWZVUL44nM5b1w32vemnDclNTD/VIXWXRHEDdCaeylk9JlfLBob47oCBaOqA2E55JAe3ZFr3MpIKD29lMoY9qfH9EKvEAS7HFi9Yh5SZ3qkPcIrs1LJZZlA7g4PFmVY5a8+uU45nDDtZer1aWiw18hGW4N86dNOLRE6z3q5br9qKskbnKzCyk/XSKFalSczVzyYAW1gUNh29VxQzZ6SUKBtBjIdbgJmtQMJkw4wiHFUrxWeodddmDVhI7tIkVG5WX8X5D5Gf8BGDwu5w1Qdj6h2huuEPvcaGi0BeX6CQdSaXwxtjr3EODQGwOv0Lu3l0vZW0UA+i6JKfUcrCSudpEAnmWbh5gGXpqanF4s+b1GmyT3QWg02tpFAJbDmqoVD358QhCPLLGKPEW0MaAWRBpqIB0eVc5+YPYKEVKadTqWAPHs3l30aK/g8B2bs8=
