language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
    secure: NgCVaB3MeqfyVnnrqOVc5L6lWeGT8sIIHK8wlnR3sY5jxULyYBRg7UDy+1oLBsA+P1nIETOqIrmRqLJxOT12ctSUHGG1SX24UrFyezqhaBO7zsbyzCO7ih4zc384Zqa0mp2KRjckkaizOy5HuoRqrBGPLRYNrv93m12SRSq04y8TELuTy4736/wUimxUNfPUqH6wX1Z+uOvIrB6LQJU1leceLor1W6cC5LSuMknXcqhlCmn3dvnLmfTs1xXQrGDXWJQgTZNzpb+FXPWrSri/KTHrb4rRxP7cT1rPYPhIAUrxswTbd4lmBTRjoQK6HmIPQ2hHr7hxSWRl/EPME5WRUquyqCnIBO2odfKdxLdDLZK1qlcjB2srjq9ycTdchp1RMTEpgt1dM8z+IKJ7mUzrR68DJP7cM1ntKVtIVNFDG+rwPWkP172kwoR5fWjjns9YF+HrvhwN2fx6qv58oKlfuprPNEfr1ms7MR4STrvUrNbGCGjIvdDFZjuBhFFgD/rGV/L74fIViyJX5XbuWA3sJFZgur2I9EKAqmLpFCy7q9p2G6blwDjU5MF/lRJR+QDYa3r0PWZladYx0jsBIg/5JPR8H45okyFFHQskVtldkl6GCJnGR1a3ZDU0slDkuxrUKV0pq1QsFbxPue0mZSNAhWP/JqsZ5u5ZwDuTRVYpKQ4=
