language: python
python:
- 3.6
addons:
  apt:
    packages:
    - unzip
install:
- make install
script:
- make test
branches:
  only:
  - l5han
env:
  global:
    secure: HNotvzMhFJmylCuort6Q+oo9Cgph4c6a6VAwNpkRJmVZNwvoZwMjT1ht9HCLL/Ux3xWhpnqznFVZHL2K+BzrbE1cP1atg2O7ih30niq0EQF+XNHEA5LqTPppkLAi+JoP9IX+WEmcAWGvQs40tysckwaAmqLtbMXVIzuss5i6dKxpQ/oGT+g+Tn5uw/eE1A/kIu5zrELNV4FCkq6ng5Vm31BhhtwO9FSQXxYuB3eU670a9RxFhvA9wXWUqOpCLyRI/6ciETyo/v19hOeWlZ1INEKF4rGgIoi1a8gt/e9qJCh8XUuRhVYjPYeqzJnFIj4skd0rHeIOKMdBvETTinzTv1E7py7N3lNob+uSCl+8PtOu9xnTWnyN8vADWoDsLyKPEtFU3S3CgemI3OhL5l3sSBQgZR5HohH65MGcv3K+CciC6ip7y8Ui12kENdLP3cf6i7gvYEaaz3U59ZG9jTjM1vfJYjbKpfHulQrCWN61bVYryUjz+0WgGG3Wb8qDFbegUwiDQZzEahbWWao27kR3a/ppU1qiL8V2eGlhhqHoKLhIXGHXP6LzEWUrFRs5k1nmRUCAZdEmSJTJB2BVMtbwDxj7x7ANw/6lbCzwNyBH3VJRIEYYLYFhJocpf5TBvRSXgptemeBgtRolw3oW2DLTwQvHzD4sz9WrI6NYAS4ewyU=
